name: package:google_generative_ai

permissions: read-all

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/google_generative_ai.yml'
      - 'pkgs/google_generative_ai/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/google_generative_ai.yml'
      - 'pkgs/google_generative_ai/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/google_generative_ai
    strategy:
      fail-fast: false
      matrix:
        sdk: ['3.1', stable, dev]
        include:
          - sdk: stable
            run-tests: true
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart pub get

      - run: dart analyze --fatal-infos

      # Make sure that the package version in lib/src/version.dart is kept up-to-date.
      - run: dart tool/validate_version.dart

      - run: dart format --output=none --set-exit-if-changed .
        if: ${{matrix.run-tests}}

      - run: dart test
        if: ${{matrix.run-tests}}

      - run: dart test --platform chrome
        if: ${{matrix.run-tests}}
